"""Storage boundary for everything the planner reads and writes.

The planner used to `open()` and `json.load()` its own files inline, which
meant the file layout was baked into the business logic in a dozen places. All
of that now goes through a `PlanRepository`, so swapping local JSON for a
backend service is a matter of writing one more subclass — no caller changes.

**Every method is `async` on purpose, including the local file
implementation.** The interface is written for the future backend (which will
receive asynchronous webhook pushes and must not block an event loop), not for
today's filesystem: making the local implementation sync "because files are
fast" would put an `await` boundary in exactly the wrong place and force every
caller to change again later. `LocalJSONRepository` therefore does its blocking
`open()`/`json` work in a worker thread via `asyncio.to_thread`, so awaiting it
genuinely yields to the loop rather than just wrapping a blocking call in a
coroutine.

The repository deliberately deals in plain dicts/lists, never in `WeekPlan` or
`WeekSpec`: `planner` imports this module, so importing planner's models back
here would be a cycle. Callers do their own `WeekPlan.model_validate(...)`,
which also keeps schema validation a business-logic concern rather than a
storage one.
"""

import abc
import asyncio
import hashlib
import json
import os
import uuid
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Awaitable, Dict, List, Optional, TypeVar

# Anchored on this file, never on the working directory. The code lives in
# `src/` and everything it reads one level up, so a relative "config/week.json"
# would only resolve when the process happened to start in the project root —
# which is exactly what `./scripts/server.sh` does *not* guarantee, and what a
# bare `cd src && python planner.py` breaks. Two `dirname`s up from
# `src/repository.py` is the project root by construction.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Four directories, split by *who writes the file*, because that is the
# question a reader actually has when looking for the knob to turn:
#   config/     hand-edited. Change these to change what the app does.
#   reference/  shipped corpora. Read-only in practice, tracked in git.
#   data/       written by the app. Never hand-edit; regenerated by use.
#   logs/       written by the app, disposable.
# The payoff is that `data/` and `logs/` are ignorable wholesale — when a
# directory needs per-file .gitignore exceptions it is still mixing lifecycles.
CONFIG_DIR = os.path.join(PROJECT_ROOT, "config")
REFERENCE_DIR = os.path.join(PROJECT_ROOT, "reference")
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
LOGS_DIR = os.path.join(PROJECT_ROOT, "logs")

# Which config file owns which top-level key — the manifest `_read_config`
# merges against. The merged result is the single flat dict `AppConfig` has
# always validated, so nothing downstream of the repository knows the config
# arrived in six pieces.
#
# Adding a field to `AppConfig` means adding it here too, and the merge will
# say so if you forget. That coupling is deliberate: a new key has to belong
# to *some* file, and answering "which one" at the time it is added is the
# whole point of the split.
CONFIG_FILES = {
    # The body being planned for, and the numbers it is aimed at.
    "profile.json": (
        "user_profile",
        "target_modes",
        "weekly_schedule",
        "meal_weights",
        "dietary_rules",
    ),
    # What a meal may be: the vocabulary generation draws from.
    "meals.json": (
        "meal_types",
        "meal_styles",
        "cuisines",
        "cuisine_affinities",
        "cuisine_meal_types",
        "baseline_cuisines",
        "diet_styles",
        "week_defaults",
    ),
    # The shape of a week and the logistics around it.
    "week.json": (
        "week_start_day",
        "shopping",
        "serving_rules",
        "enable_sunday_prep",
        "max_prep_active_mins",
        "inventory_to_clear",
        "inventory_rules",
    ),
    # Where you are and what you are doing — the *declared* week. An
    # integration that later observes any of this writes a cache into `data/`
    # and wins for the days it covers; this file stays the standing default.
    "schedule.json": (
        "training_schedule",
        "base_schedule",
        "location_rules",
        "regional",
        "sourcing",
    ),
    # Tuning for the planner itself rather than for the food.
    "engine.json": ("planning_rules", "ui_settings"),
}

# Reverse index, so a misfiled key produces "belongs in profile.json, found in
# meals.json" instead of `extra="forbid"`'s anonymous rejection.
CONFIG_KEY_OWNER = {
    key: filename for filename, keys in CONFIG_FILES.items() for key in keys
}

T = TypeVar("T")

# The three lists biometrics.json holds, and the shape `load_biometrics`
# promises its callers even when the file is absent or half-written. All three
# are keyed by an ISO "YYYY-MM-DD" `date`, which is what makes a re-post for a
# day an update rather than a duplicate row.
#
# `readiness_log` is the newest and is a third *signal*, not a field on a
# weigh-in: a scale and a watch can both report for the same date, and folding
# sleep into `weigh_ins` would let the two silently overwrite each other with
# no way to tell which won — the identical reasoning that keeps `weigh_ins`
# and `daily_actuals` apart. A file written before it existed simply has no
# such key, which `_read_biometrics` reads as an empty list.
BIOMETRIC_SECTIONS = ("weigh_ins", "daily_actuals", "readiness_log")

# Which sync source fills which of those lists. Here rather than in
# `integrations/sync_service.py`, where it started, because it is a fact about
# the file's layout — the same kind of thing `BIOMETRIC_SECTIONS` above already
# states — and it now has two readers with nothing else in common: the catchup
# walk (`get_sync_date_range`, deciding which dates anchor a source's range)
# and the Settings destination's sync-status view (deciding which section's
# rows a source's checkpoint should be diffed against). A second copy in the
# UI would be free to disagree about which source writes what, and would do so
# silently — the read view would simply report the wrong list as empty.
#
# **It is one-to-many, and has been since `readiness_log` arrived**: one
# Garmin sync fills both `weigh_ins` and `readiness_log`, off the same login
# and under the same `sync_checkpoints["garmin"]` entry. Both readers were
# written against a one-section-per-source assumption and both had to stop
# assuming it — `get_sync_date_range` now folds a source's sections together
# before taking its latest date, and the sync view names its cards by section
# rather than by source, or two of the three would have read "Garmin".
BIOMETRIC_SECTION_SOURCES = {
    "weigh_ins": "garmin",
    "daily_actuals": "cronometer",
    "readiness_log": "garmin",
}


@dataclass(frozen=True)
class StoragePaths:
    """Where every file the app reads or writes lives.

    The single source of truth for these names — before this existed,
    `ui_app.py` and `planner.py` each redeclared "config.json"/"week_plan.json"
    as their own module constants, and the two copies were free to drift from
    whatever `LocalJSONRepository` actually defaulted to. Callers that need a
    path (a CLI `--help` string, a "loading from X" message) read it off a
    `LocalJSONRepository`'s `.paths` instead of naming the file themselves.

    Four directories in, individual files *derived* rather than stored. That
    is what keeps this a four-field dataclass instead of the thirteen-argument
    constructor one-field-per-file would now need, and it means overriding a
    directory moves everything in it — pointing `data_dir` at a temp folder
    relocates the week plan, the history and the catalog together, which is
    what a test relocating storage actually wants.

    There is no `favorites` entry: favoriting doesn't have its own file, it's
    an `is_favorite` flag on an entry in `recipe_catalog`
    (`recipes_master.json`) — adding a path here that nothing ever reads or
    writes would just be a second, misleading name for that same file.
    """

    config_dir: str = CONFIG_DIR
    reference_dir: str = REFERENCE_DIR
    data_dir: str = DATA_DIR
    logs_dir: str = LOGS_DIR
    # Measured body composition and logged macro actuals — see
    # `PlanRepository.load_biometrics`. One file rather than two because the
    # weigh-in and the day it belongs to are always read together. The one
    # per-file override kept, because `test_sync_service` relocates exactly
    # this file and nothing else.
    biometrics_override: Optional[str] = None

    # -- config/ ------------------------------------------------------------

    @property
    def config_files(self) -> List[str]:
        """Absolute path to each file in `CONFIG_FILES`, merge order."""
        return [os.path.join(self.config_dir, name) for name in CONFIG_FILES]

    @property
    def models(self) -> str:
        return os.path.join(self.config_dir, "models.json")

    @property
    def integrations(self) -> str:
        return os.path.join(self.config_dir, "integrations.json")

    # -- reference/ ---------------------------------------------------------

    @property
    def whfoods(self) -> str:
        return os.path.join(self.reference_dir, "whfoods.json")

    # -- data/ --------------------------------------------------------------

    @property
    def history(self) -> str:
        return os.path.join(self.data_dir, "meal_history.json")

    @property
    def week_plan(self) -> str:
        return os.path.join(self.data_dir, "week_plan.json")

    @property
    def recipe_catalog(self) -> str:
        return os.path.join(self.data_dir, "recipes_master.json")

    @property
    def biometrics(self) -> str:
        return self.biometrics_override or os.path.join(self.data_dir, "biometrics.json")

    @property
    def rejections(self) -> str:
        """Why a suggestion was regenerated away — see CLAUDE.md's "Rejection
        capture". A flat, append-only event log, not upsert-by-date like
        `biometrics`: two rejections can land on the same slot on the same
        day (regenerate twice), and there's nothing to merge them on."""
        return os.path.join(self.data_dir, "rejections.json")

    @property
    def shopping_list(self) -> str:
        """Not JSON state like the rest — an export the CLI's
        --save-shopping-list writes for a human to read. It lives here anyway
        because the whole point of this module is that no file path is spelled
        out anywhere else."""
        return os.path.join(self.data_dir, "shopping_list.md")

    # -- logs/ --------------------------------------------------------------

    @property
    def generation_log(self) -> str:
        return os.path.join(self.logs_dir, "meals.log")


def recipe_content_key(recipe: dict) -> str:
    """Identity for "is this the same recipe" purposes: name + ingredient
    composition, not object identity or a generated id.

    This is what makes favoriting idempotent across regenerations — cooking
    the same dish again next month (same name, same grams of each
    ingredient) resolves to the same catalog entry rather than a duplicate,
    while a same-named dish with different ingredients is treated as a
    genuinely different recipe. Quantities are rounded to 2dp before hashing
    so float noise from portion trimming can't split one recipe into two
    entries.
    """
    name = (recipe.get("name") or "").strip().lower()
    ingredients = sorted(
        (
            (ingredient.get("name") or "").strip().lower(),
            round(float(ingredient.get("quantity_g") or 0), 2),
        )
        for ingredient in recipe.get("ingredients", [])
    )
    payload = json.dumps([name, ingredients], sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


# The meal-type spelling that means "don't filter by meal type". The Library
# destination's select needs a real option to sit in its list, so it says
# "All"; a query string just leaves the parameter off, so the API says None.
# Both spellings are handled by `catalog_matches` below rather than by its
# callers, which is the whole point of there being one function.
CATALOG_MEAL_TYPE_ANY = "All"


def catalog_matches(
    entry: dict,
    *,
    favorites_only: bool = False,
    meal_type: Optional[str] = None,
    search: Optional[str] = None,
) -> bool:
    """Whether one `recipe_catalog` record passes the three filters every
    catalog reader offers: favorites-only, meal-type equality, and a
    case-insensitive substring on the name.

    It lives here, beside `recipe_content_key`, for the reason
    `BIOMETRIC_SECTION_SOURCES` does: it is a fact about the shape of a
    stored record, and it now has two readers with nothing else in common —
    `api.py`'s `/api/recipes` and `ui_catalog_browser`'s grid. Those two used
    to carry a copy each, free to disagree *silently*, since a drifted filter
    returns a differently-filtered list rather than an error. They had
    already drifted over what "no meal-type filter" is spelled as; that is
    now one constant above rather than two conventions.

    A UI module would have been the other home, but the API deliberately
    imports nothing from `ui_*` — see `api.py`'s docstring — and this needs
    no `PlannerState`, no `UIContext` and no NiceGUI.
    """
    if favorites_only and not entry.get("is_favorite"):
        return False
    recipe = entry.get("recipe") or {}
    if meal_type and meal_type != CATALOG_MEAL_TYPE_ANY:
        if recipe.get("meal_type") != meal_type:
            return False
    needle = (search or "").strip().lower()
    if needle and needle not in (recipe.get("name") or "").lower():
        return False
    return True


class PlanRepository(abc.ABC):
    """Everything the planner needs to persist, as an async interface.

    Implementations must tolerate missing data the way the local files always
    have: an absent history is an empty list, an absent week plan is None. A
    missing *config* is an error — there is no sensible default for it, and
    silently planning against `{}` would be worse than failing loudly.
    """

    @abc.abstractmethod
    async def load_config(self) -> dict:
        """Targets, dietary rules, styles, cuisines. Raises if unavailable."""

    @abc.abstractmethod
    async def save_config_keys(self, updates: dict) -> None:
        """Write top-level config keys back to whichever file owns each.

        The one write path into `config/`, and the only place in the app
        besides generation that persists anything. It exists because a
        *setting* is not a per-week input: `target_modes` answers "where do
        my numbers come from", and a toggle that reset on every page reload
        would answer it differently each time you looked.

        Deliberately narrow — it merges the keys it is given into the file
        `CONFIG_FILES` says owns them and leaves every other key in that file
        alone. It is not a general "save the config" call, because the config
        the app holds in memory is a *merged* dict carrying runtime-injected
        keys (`training_uplift`, `nudge_foods`, `openrouter_model`) that must
        never reach disk.
        """

    @abc.abstractmethod
    async def load_models_config(self) -> dict:
        """Model selection and LLM call parameters (models.json).

        Unlike `load_config`, a missing file is not an error: this data is
        supplemental defaults (which model, which timeout), every one of
        which already has an in-code fallback, so a fresh install with no
        `models.json` yet must plan exactly as it did before this file
        existed, not fail to start. Implementations return `{}` when the file
        is absent.
        """

    @abc.abstractmethod
    async def load_integrations_config(self) -> dict:
        """Tuning for the sync integrations (integrations.json).

        Supplemental like `load_models_config`, and absent-means-`{}` for the
        same reason: every value here has an in-code default, and a checkout
        that never syncs anything must not need the file.

        Only *tuning* belongs here. Credentials stay in `.env`, and the
        payloads a sync fetches are written to `data/` — this file is the
        declared half of an integration, never the observed half.
        """

    @abc.abstractmethod
    async def load_whfoods(self) -> List[str]:
        """Names of the nutrient-dense whole foods in whfoods.json, flattened
        out of their category grouping.

        Supplemental, like `load_models_config`: a fresh install or an older
        checkout without whfoods.json must still plan exactly as it did
        before this file existed, so implementations return `[]` when the
        file is absent rather than raising.
        """

    @abc.abstractmethod
    async def load_history(self) -> List[dict]:
        """Past days, oldest first. Empty when nothing has been generated yet.

        This is what seeds style/cuisine rotation and the recent-protein list,
        so an empty result is a valid cold start, not a failure.
        """

    @abc.abstractmethod
    async def save_history(self, history: List[dict]) -> None:
        """Replace the stored history with `history` (already trimmed by the
        caller to its max length)."""

    @abc.abstractmethod
    async def load_rejections(self) -> List[dict]:
        """Every recorded `planner.RejectionEntry`, oldest first. Empty when
        nothing has been recorded yet — the normal state until a user first
        hits regenerate and picks a reason.

        Separate from `daily_actuals`/`weigh_ins` for the same reason
        CLAUDE.md's biometric-sync section keeps those two apart: this is a
        different signal (why a suggestion was refused before it ever became
        the plan) from anything else already stored, and folding it into an
        existing key would let the two silently overwrite each other with no
        way to tell which won.
        """

    @abc.abstractmethod
    async def save_rejection_entry(self, entry: dict) -> None:
        """Append one rejection. Unlike `save_biometric_entry`, this never
        merges into an existing row — two rejections can land on the same
        slot on the same day (regenerate twice in a row), and each is its own
        event, not an update to the last one."""

    @abc.abstractmethod
    async def load_biometrics(self) -> dict:
        """Measured body composition, logged macro actuals and overnight
        readiness, as `{"weigh_ins": [...], "daily_actuals": [...],
        "readiness_log": [...], "sync_checkpoints": {...}}`, each list oldest
        first.

        The measured counterpart to `config.json`'s `user_profile`: the profile
        says what the body is aiming at, this says where it actually is, and an
        adaptive target is the difference between them. Both lists are keyed by
        an ISO `date` — `weigh_ins` records what the scale reported
        (`weight_kg` plus optional `body_fat_pct`, `muscle_mass_kg`,
        `water_pct`, `bmi`), `daily_actuals` what was really eaten
        (`calories`, `protein_g`, `net_carbs_g`, `fat_g`, `fiber_g` — the
        four budgeted macros plus the one that is only ever reported), and
        `readiness_log`
        how the night before went (`sleep_score`, `sleep_hours`, `hrv_ms`,
        `readiness_label`).

        **Nothing in `readiness_log` is energy**, and its separation from the
        other two is what keeps it that way: a sleep score is a unitless
        0-100 index and an HRV figure is milliseconds, so no arithmetic could
        legitimately turn either into kcal. See `sync_service.fetch_readiness`.

        `sync_checkpoints` (`{"garmin": "2026-08-25", ...}`) is not a
        measurement at all — see `save_sync_checkpoint`.

        A missing file is an empty result, not an error — the same cold-start
        tolerance `load_history` extends, and for the same reason: no weigh-ins
        yet is the normal state of a fresh install, not a failure. All three
        keys are always present in the returned dict, so callers index them
        directly.
        """

    @abc.abstractmethod
    async def save_biometric_entry(self, entry: dict) -> None:
        """Record one weigh-in, replacing any existing entry for its `date`.

        Upsert rather than append because a smart scale is perfectly happy to
        report twice in a morning, and two rows for one day would silently
        double-count in any trend read over the series. `entry` must carry a
        `date`; without one it could never be corrected or superseded, so it
        is rejected rather than stored unaddressable.

        Fields absent from `entry` are left as they were on an existing row,
        so a hand-typed body-fat correction doesn't blank out the weight the
        scale already recorded. A key present with `None` is still an
        overwrite — explicit beats remembered.
        """

    @abc.abstractmethod
    async def save_daily_actuals(self, entry: dict) -> None:
        """Record what was actually eaten on a day, replacing any existing
        entry for its `date`. Same upsert-by-date and same merge semantics as
        `save_biometric_entry` — a day logged meal by meal arrives as several
        calls, and each must refine the day rather than start a second one.
        """

    @abc.abstractmethod
    async def save_readiness_entry(self, entry: dict) -> None:
        """Record how a night went, replacing any existing entry for its
        `date`. Same upsert-by-date and same merge semantics as
        `save_biometric_entry`.

        Its own list rather than a few more keys on the weigh-in row, for the
        reason `BIOMETRIC_SECTIONS` states: the scale and the watch are two
        devices reporting about one date, and one merged row would let a
        partial answer from either blank the other's.

        Merging is what makes the split fetch safe, too — sleep and HRV come
        from two different Garmin endpoints and either can fail on its own, so
        a re-sync that gets the one that failed last time refines the row
        rather than starting a second one.
        """

    @abc.abstractmethod
    async def get_latest_biometrics(self) -> Optional[dict]:
        """The most recent weigh-in by `date`, or None if there are none yet.

        Its own method rather than `load_biometrics()["weigh_ins"][-1]` at
        every call site: "latest" is a question about dates, not list order,
        and a backend that returns rows in insertion order — or a file someone
        hand-edited — would make the index answer confidently wrong.
        """

    @abc.abstractmethod
    async def save_sync_checkpoint(self, source: str, checked_date: str) -> None:
        """Record that `source` (e.g. `"garmin"`, `"cronometer"`) was checked
        through `checked_date`, independent of whether anything was found.

        Every list here only ever holds a *measured* day — a forgotten
        weigh-in, an unlogged day, a night the watch wasn't worn — none of
        them write a row at all, by design (see `save_biometric_entry`). That
        is correct for the lists, and wrong for
        `sync_service.get_sync_date_range`'s gap-finding: without a
        separate record of what was actually *looked at*, a genuinely empty
        day is indistinguishable from one nobody ever checked, and the
        catchup walk re-requests it forever.

        One checkpoint per *source*, not per list, which is what a
        one-to-many `BIOMETRIC_SECTION_SOURCES` implies: one Garmin login
        answers for the scale and the watch in a single pass, so there is one
        "asked about this date" fact to record. The consequence is that a
        date checked before `readiness_log` existed is marked checked for it
        too — see `ui_state.sync_status`, which says so on the page rather
        than inventing a second checkpoint to paper over it.

        Monotonic — never moves `source`'s checkpoint backward. A manual
        `--date` re-sync of an older day, or a catchup run that resolves an
        earlier date after a later one already landed, must not un-teach the
        process what it already confirmed about a more recent day.
        """

    @abc.abstractmethod
    async def load_week_plan(self, week_identifier: str = "current") -> Optional[dict]:
        """The last generated week as a raw dict, or None if there isn't one.

        `week_identifier` picks which cached week — `"current"` (the default,
        and the only one that existed before multi-week support) or `"next"`
        — since the app now keeps two weeks on disk at once rather than
        overwriting a single file. Returned unvalidated so this module stays
        independent of planner's Pydantic models; callers run
        `WeekPlan.model_validate` themselves.
        """

    @abc.abstractmethod
    async def save_week_plan(self, week_plan: dict, week_identifier: str = "current") -> None:
        """Store the generated week under `week_identifier`, replacing any
        previous plan stored under that same identifier.

        Not in the original four methods, but the cached week plan is the other
        half of `load_week_plan` and the CLI's `--use-cached-plan` flag reads
        what this writes — leaving it out would have left a bare `json.dump`
        behind in planner.py, which is the thing this module exists to remove.
        """

    @abc.abstractmethod
    async def save_shopping_list(self, markdown: str) -> None:
        """Write the CLI's rendered shopping list (`--save-shopping-list`).

        The last thing in the app that still used a bare `open()` outside this
        module, which quietly made the "nothing else touches a file" boundary
        untrue. A backend implementation would put this somewhere a phone can
        reach rather than next to the code, which is exactly the kind of change
        this interface exists to absorb.
        """

    @abc.abstractmethod
    async def load_recipe_catalog(self) -> List[dict]:
        """Every recipe ever favorited or imported, oldest first — the single
        store recipe content lives in outside of the current `week_plan.json`.

        Records look like `{id, content_key, recipe, is_favorite, source,
        added_at, updated_at}`. `week_plan.json` and `meal_history.json` are
        not this store: the former is overwritten every generation and the
        latter keeps only lean per-day summaries, so a recipe that isn't
        favorited or imported has no life beyond the week it was cooked in.
        """

    @abc.abstractmethod
    async def get_favorites(self) -> List[dict]:
        """The subset of the catalog with `is_favorite` true."""

    @abc.abstractmethod
    async def toggle_favorite(self, recipe: dict) -> bool:
        """Flip favorite status for the catalog entry matching `recipe`'s
        name + ingredients (see `recipe_content_key`).

        If no matching entry exists yet, one is created (`source="favorited"`,
        already favorited) — the first click on a card's bookmark is both
        "add to catalog" and "favorite it" in one step. An existing entry is
        never removed by this call, only its flag flipped, so un-favoriting a
        recipe never drops it from the catalog (see `delete_catalog_recipe`
        for actual removal). Returns the new `is_favorite` state.
        """

    @abc.abstractmethod
    async def import_recipe(self, recipe: dict, favorite: bool = False) -> dict:
        """Add `recipe` to the catalog (`source="imported"`), or fold into a
        matching existing entry (see `recipe_content_key`) if one exists.

        `favorite` can only ever turn an existing entry's flag on, never off
        — an import is not how a recipe gets un-favorited. Returns the
        stored record.
        """

    @abc.abstractmethod
    async def rename_catalog_recipe(self, recipe_id: str, name: str) -> Optional[dict]:
        """Rename a catalog entry's recipe in place. Returns the updated
        record, or None if `recipe_id` isn't in the catalog — a favorite
        deleted in another tab is a no-op here, not an error, the same
        tolerance `load_history`/`load_week_plan` extend to a missing file.
        """

    @abc.abstractmethod
    async def delete_catalog_recipe(self, recipe_id: str) -> None:
        """Remove an entry from the catalog outright. A no-op if already
        gone. Distinct from `toggle_favorite`'s un-favorite, which keeps the
        entry — this is for discarding a bad import or a mistaken save."""


class LocalJSONRepository(PlanRepository):
    """The current on-disk layout: JSON files in the project's `data/`
    directory, one level up from this module's `src/`.

    Paths are constructor arguments rather than module constants so tests (and
    a second week in another directory) don't have to chdir. Writes go to a
    temporary file and are then renamed: a crash mid-write would otherwise
    leave truncated JSON where meal_history.json used to be, and history is not
    reproducible once lost.
    """

    def __init__(
        self,
        config_dir: str = CONFIG_DIR,
        reference_dir: str = REFERENCE_DIR,
        data_dir: str = DATA_DIR,
        logs_dir: str = LOGS_DIR,
        biometrics_path: Optional[str] = None,
    ) -> None:
        self.paths = StoragePaths(
            config_dir=config_dir,
            reference_dir=reference_dir,
            data_dir=data_dir,
            logs_dir=logs_dir,
            biometrics_override=biometrics_path,
        )

    # -- PlanRepository ----------------------------------------------------

    async def load_config(self) -> dict:
        return await asyncio.to_thread(self._read_config)

    def _read_config(self) -> dict:
        """The files in `CONFIG_FILES`, merged into one flat dict.

        Every key is checked against the manifest on the way in, so the three
        ways a hand-edited split config goes wrong each fail here with the
        filename in the message, rather than as `AppConfig`'s `extra="forbid"`
        rejection (which knows the key is unwanted but not where it should
        have gone) or — worse — as a key that silently defaults because the
        file holding it was never read.

        A missing file is an error, not an empty dict: every one of these
        carries keys with no safe default, and planning a week against a
        silently-defaulted `weekly_schedule` is the exact failure the loud
        `load_config` contract exists to prevent.
        """
        merged: dict = {}
        provided_by: dict = {}
        missing = []

        for filename, owned in CONFIG_FILES.items():
            path = os.path.join(self.paths.config_dir, filename)
            contents = self._read_json(path)
            if contents is None:
                missing.append(path)
                continue
            if not isinstance(contents, dict):
                raise ValueError(f"{path} must contain a JSON object, got {type(contents).__name__}")
            for key, value in contents.items():
                if key in provided_by:
                    raise ValueError(
                        f"'{key}' is defined twice: in {provided_by[key]} and in {filename}. "
                        "One key, one file."
                    )
                owner = CONFIG_KEY_OWNER.get(key)
                if owner is None:
                    raise ValueError(
                        f"'{key}' in {filename} is not a known config key. Add it to "
                        "CONFIG_FILES in repository.py (and to AppConfig) if it is new."
                    )
                if owner != filename:
                    raise ValueError(
                        f"'{key}' belongs in {owner}, found in {filename}."
                    )
                merged[key] = value
                provided_by[key] = filename

        if missing:
            raise FileNotFoundError(
                "Config file(s) not found: " + ", ".join(missing)
            )
        return merged

    async def save_config_keys(self, updates: dict) -> None:
        await asyncio.to_thread(self._save_config_keys, updates)

    def _save_config_keys(self, updates: dict) -> None:
        """Merge `updates` into the config files that own its keys.

        Read-modify-write per file rather than a whole-config rewrite, so a
        key this app has never heard of — added by hand to profile.json — is
        preserved rather than silently dropped on the next settings change.
        An unknown key raises for the same reason `_read_config` does: it
        belongs in *some* file, and guessing is what leaves a value written
        somewhere nothing reads it back from.
        """
        by_file: Dict[str, dict] = {}
        for key, value in updates.items():
            owner = CONFIG_KEY_OWNER.get(key)
            if owner is None:
                raise ValueError(
                    f"'{key}' is not a known config key. Add it to CONFIG_FILES "
                    "in repository.py (and to AppConfig) if it is new."
                )
            by_file.setdefault(owner, {})[key] = value

        for filename, changes in by_file.items():
            path = os.path.join(self.paths.config_dir, filename)
            contents = self._read_json(path)
            if not isinstance(contents, dict):
                raise ValueError(
                    f"{path} must contain a JSON object before it can be updated."
                )
            self._write_json(path, {**contents, **changes})

    async def load_models_config(self) -> dict:
        return await asyncio.to_thread(self._read_json, self.paths.models) or {}

    async def load_integrations_config(self) -> dict:
        return await asyncio.to_thread(self._read_json, self.paths.integrations) or {}

    async def load_whfoods(self) -> List[str]:
        foods = await asyncio.to_thread(self._read_json, self.paths.whfoods) or []
        return [food["name"] for food in foods if food.get("name")]

    async def load_history(self) -> List[dict]:
        return await asyncio.to_thread(self._read_json, self.paths.history) or []

    async def save_history(self, history: List[dict]) -> None:
        await asyncio.to_thread(self._write_json, self.paths.history, history)

    async def load_rejections(self) -> List[dict]:
        return await asyncio.to_thread(self._read_json, self.paths.rejections) or []

    async def save_rejection_entry(self, entry: dict) -> None:
        await asyncio.to_thread(self._append_rejection, entry)

    async def load_biometrics(self) -> dict:
        return await asyncio.to_thread(self._read_biometrics)

    async def save_biometric_entry(self, entry: dict) -> None:
        await asyncio.to_thread(self._upsert_dated_entry, "weigh_ins", entry)

    async def save_daily_actuals(self, entry: dict) -> None:
        await asyncio.to_thread(self._upsert_dated_entry, "daily_actuals", entry)

    async def save_readiness_entry(self, entry: dict) -> None:
        await asyncio.to_thread(self._upsert_dated_entry, "readiness_log", entry)

    async def get_latest_biometrics(self) -> Optional[dict]:
        weigh_ins = (await self.load_biometrics())["weigh_ins"]
        if not weigh_ins:
            return None
        return max(weigh_ins, key=lambda row: row.get("date") or "")

    async def save_sync_checkpoint(self, source: str, checked_date: str) -> None:
        await asyncio.to_thread(self._save_sync_checkpoint, source, checked_date)

    async def load_week_plan(self, week_identifier: str = "current") -> Optional[dict]:
        return await asyncio.to_thread(
            self._read_json, self._week_plan_path(week_identifier)
        )

    async def save_week_plan(self, week_plan: dict, week_identifier: str = "current") -> None:
        await asyncio.to_thread(
            self._write_json, self._week_plan_path(week_identifier), week_plan
        )

    async def save_shopping_list(self, markdown: str) -> None:
        await asyncio.to_thread(self._write_text, self.paths.shopping_list, markdown)

    async def load_recipe_catalog(self) -> List[dict]:
        return await asyncio.to_thread(self._read_json, self.paths.recipe_catalog) or []

    async def get_favorites(self) -> List[dict]:
        catalog = await self.load_recipe_catalog()
        return [record for record in catalog if record.get("is_favorite")]

    async def toggle_favorite(self, recipe: dict) -> bool:
        return await asyncio.to_thread(self._toggle_favorite, recipe)

    async def import_recipe(self, recipe: dict, favorite: bool = False) -> dict:
        return await asyncio.to_thread(self._import_recipe, recipe, favorite)

    async def rename_catalog_recipe(self, recipe_id: str, name: str) -> Optional[dict]:
        return await asyncio.to_thread(self._rename_catalog_recipe, recipe_id, name)

    async def delete_catalog_recipe(self, recipe_id: str) -> None:
        await asyncio.to_thread(self._delete_catalog_recipe, recipe_id)

    def _week_plan_path(self, week_identifier: str) -> str:
        """File for one named week.

        `"current"` maps to the original single-file layout
        (`self.paths.week_plan`, i.e. `week_plan.json`) rather than
        `week_plan_current.json`, so an existing install with a cached week
        already on disk needs no migration and no data movement the first
        time this runs. Every other identifier — `"next"`, or a week-start
        date — gets its own `week_plan_<identifier>.json` alongside it.

        "Alongside" means *in the same directory as* `self.paths.week_plan`,
        derived rather than spelled out. A literal `f"week_plan_{id}.json"`
        was silently relative to the working directory: `"current"` would
        load from `data/` while `"next"` wrote to wherever the process
        started, so the two weeks lived in different folders.
        """
        if week_identifier == "current":
            return self.paths.week_plan
        return os.path.join(
            os.path.dirname(self.paths.week_plan),
            f"week_plan_{week_identifier}.json",
        )

    # -- blocking helpers, only ever called in a worker thread --------------

    def _find_catalog_entry(self, catalog: List[dict], recipe: dict) -> Optional[dict]:
        key = recipe_content_key(recipe)
        return next((r for r in catalog if r.get("content_key") == key), None)

    def _toggle_favorite(self, recipe: dict) -> bool:
        catalog = self._read_json(self.paths.recipe_catalog) or []
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        existing = self._find_catalog_entry(catalog, recipe)
        if existing is not None:
            existing["is_favorite"] = not existing.get("is_favorite", False)
            existing["updated_at"] = now
            new_state = existing["is_favorite"]
        else:
            catalog.append(
                {
                    "id": uuid.uuid4().hex,
                    "content_key": recipe_content_key(recipe),
                    "recipe": recipe,
                    "is_favorite": True,
                    "source": "favorited",
                    "added_at": now,
                    "updated_at": now,
                }
            )
            new_state = True
        self._write_json(self.paths.recipe_catalog, catalog)
        return new_state

    def _import_recipe(self, recipe: dict, favorite: bool) -> dict:
        catalog = self._read_json(self.paths.recipe_catalog) or []
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        existing = self._find_catalog_entry(catalog, recipe)
        if existing is not None:
            if favorite and not existing.get("is_favorite", False):
                existing["is_favorite"] = True
                existing["updated_at"] = now
            record = existing
        else:
            record = {
                "id": uuid.uuid4().hex,
                "content_key": recipe_content_key(recipe),
                "recipe": recipe,
                "is_favorite": favorite,
                "source": "imported",
                "added_at": now,
                "updated_at": now,
            }
            catalog.append(record)
        self._write_json(self.paths.recipe_catalog, catalog)
        return record

    def _rename_catalog_recipe(self, recipe_id: str, name: str) -> Optional[dict]:
        catalog = self._read_json(self.paths.recipe_catalog) or []
        updated = None
        for record in catalog:
            if record.get("id") == recipe_id:
                record["recipe"]["name"] = name
                record["updated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
                updated = record
                break
        if updated is not None:
            self._write_json(self.paths.recipe_catalog, catalog)
        return updated

    def _read_biometrics(self) -> dict:
        """biometrics.json, normalised to the shape `load_biometrics` promises.

        Every section is coerced to a list even when the file is missing, was
        written before that section existed, or has a null where a list
        belongs — callers index `["weigh_ins"]` unguarded, so this is the one
        place that can be wrong about it. `sync_checkpoints` gets the same
        treatment, coerced to a dict rather than a list — a checkout written
        before checkpoints existed has none, and that must read as "nothing
        checked yet", not as a missing key.
        """
        stored = self._read_json(self.paths.biometrics) or {}
        return {
            **{section: list(stored.get(section) or []) for section in BIOMETRIC_SECTIONS},
            "sync_checkpoints": dict(stored.get("sync_checkpoints") or {}),
        }

    def _upsert_dated_entry(self, section: str, entry: dict) -> None:
        """Merge `entry` into `section` on its `date`, then rewrite the file.

        Read-modify-write in a single worker-thread call, like
        `_toggle_favorite` — the read and the write must not be separated by an
        `await`, or a concurrent save would be silently dropped by whichever
        write landed second. The list is kept sorted by date so the file reads
        chronologically to a human and to a diff; ISO dates sort lexically, so
        no parsing is needed to do it.
        """
        date = entry.get("date")
        if not date:
            raise ValueError(f"A {section} entry needs a 'date': got {entry!r}")

        biometrics = self._read_biometrics()
        rows = biometrics[section]
        existing = next((row for row in rows if row.get("date") == date), None)
        if existing is not None:
            existing.update(entry)
        else:
            rows.append(dict(entry))
        rows.sort(key=lambda row: row.get("date") or "")
        self._write_json(self.paths.biometrics, biometrics)

    def _append_rejection(self, entry: dict) -> None:
        """Read-append-write in one worker-thread call, same reasoning as
        `_upsert_dated_entry` — the read and the write must not be separated
        by an `await`, or a concurrent save could be silently dropped. No
        merge key here (unlike `_upsert_dated_entry`'s `date`): every
        rejection is its own event."""
        rejections = self._read_json(self.paths.rejections) or []
        rejections.append(dict(entry))
        self._write_json(self.paths.rejections, rejections)

    def _save_sync_checkpoint(self, source: str, checked_date: str) -> None:
        """Advance `source`'s entry in `sync_checkpoints`, never backward.

        String comparison rather than a `date` parse: every checkpoint and
        every caller here already deals in ISO `YYYY-MM-DD`, which sorts
        lexically identically to chronologically — the same shortcut
        `_upsert_dated_entry`'s sort takes.
        """
        biometrics = self._read_biometrics()
        checkpoints = biometrics["sync_checkpoints"]
        if checked_date > (checkpoints.get(source) or ""):
            checkpoints[source] = checked_date
            self._write_json(self.paths.biometrics, biometrics)

    def _delete_catalog_recipe(self, recipe_id: str) -> None:
        catalog = self._read_json(self.paths.recipe_catalog) or []
        remaining = [record for record in catalog if record.get("id") != recipe_id]
        if len(remaining) != len(catalog):
            self._write_json(self.paths.recipe_catalog, remaining)

    @staticmethod
    def _read_json(path: str) -> Any:
        if not os.path.exists(path):
            return None
        with open(path, "r") as f:
            return json.load(f)

    @staticmethod
    def _write_json(path: str, payload: Any) -> None:
        LocalJSONRepository._write_text(path, json.dumps(payload, indent=2))

    @staticmethod
    def _write_text(path: str, text: str) -> None:
        """Atomic write: temp file then rename.

        A crash mid-write would otherwise leave truncated content where
        meal_history.json used to be, and history is not reproducible once
        lost. Shared by every write here so no caller can opt out of it.
        """
        temporary = f"{path}.tmp"
        with open(temporary, "w") as f:
            f.write(text)
        os.replace(temporary, path)


def run_sync(awaitable: Awaitable[T]) -> T:
    """Run one coroutine to completion from synchronous code.

    The bridge for callers that are not (yet) async themselves — today the
    CLI's `main()`, which runs top-to-bottom in a plain thread with no loop.
    `asyncio.run` covers that, but it raises if a loop is already running in
    this thread — so when there is one, the coroutine is handed to a scratch
    thread with a loop of its own. That path costs a thread, and exists only so
    an embedded caller never deadlocks; the normal case is the first branch.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(awaitable)  # type: ignore[arg-type]

    with ThreadPoolExecutor(max_workers=1) as pool:
        return pool.submit(asyncio.run, awaitable).result()  # type: ignore[arg-type]
